### ISSUE TITLE
Other Flights

### ISSUE THREAD

**Issue by Dobermaxx99** [amree/teecket#24]
Could we add other flights? Like flights from the Philippines?

**Comment by amree** [comment]
@Dobermaxx99 Can you list down the routes? For e.g: KUL -> MNL (Manila)

I'm assuming only one of the operators in this library which is AirAsia operates in your country, right?

**Comment by Dobermaxx99** [comment]
Right, we have AirAsia. I tried MNL - PPS and I got no results. This is a Local Flight. Are local flights possible to get?

**Comment by amree** [comment]
It's possible, I just need to add those destinations. I'll try adding it today if it's possible.

**Comment by Dobermaxx99** [comment]
Actually I'm more interested in learning your gem. Could you point me at the right direction where to look at?

**Comment by amree** [comment]
FYI, to add more destination, we need to add it in another repo which is https://github.com/amree/teecket-web/. This repo is the library that's being used by that repo. So, I've added the destination based on AirAsia's official website. You can check the commit at https://github.com/amree/teecket-web/commit/14f60ced98894dbea072aacb315375f7bf3c5fe1.

I guess the best way to learn for the code is by looking at this repo as the other repo is just the front end calling this library. Probably start at https://github.com/amree/teecket/blob/master/lib/teecket.rb

**Comment by amree** [comment]
I'm closing this issue as it has been resolved. Feel free to comment back if it's not solved yet.

**Comment by Dobermaxx99** [comment]
I tried running "teecket MNL PPS 01-01-2017" and it is not working. But, it is working on http://teecket.herokuapp.com/.

**Comment by Dobermaxx99** [comment]
It is now working after issuing _gem install teecket_. Thanks!
